POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RpaGVtdWxpIiwiaWQiOiI1ZThmNDljZjBlZDBmZjU0YmQxOGQ1YjIiLCJpYXQiOjE1ODY4NTc0MjR9.WcLbaCP9ogAia3TzpzxYxGPZ2JkRL9bvo__1x1NT24k

{
  "title": "14.4. blog 6",
  "author": "Jesse James",
  "url": "https://foo-bar",
  "likes": 99
}
